substitutions:
  device_name: tzspserial
  friendly_name: TZSP Serial
  device_description: Atom Lite
  esp_board: m5stack-atom

external_components:
  - source: github://Omniflux/esphome-tzsp
  - source: github://Omniflux/esphome-tzspserial

packages:
  wifi: !include common/wifi-office.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}

esp32:
  board: ${esp_board}
  framework:
    type: esp-idf

api:

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: Restart
  - platform: safe_mode
    name: Restart (Safe Mode)

uart:
  tx_pin: GPIO13
  rx_pin: GPIO14
  baud_rate: 500
  parity: EVEN

tzsp_serial:
  frame_size: 8
  symbol_timeout: 2
  inverted: true
  tzsp:
    ip: 192.168.1.10
#    port: 37008
    protocol: 255
